# Generated by Django 4.2 on 2025-11-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
