# Generated by Django 4.2 on 2025-11-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_mentor_topic_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='password_plain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='username_plain',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
