# Generated by Django 4.2 on 2025-11-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_mentor_password_plain_mentor_username_plain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
