# Generated by Django 4.2 on 2025-12-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('authorized', 'Authorized')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
