# Generated by Django 4.2 on 2025-12-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_category_student_valid_upto'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='access_type',
            field=models.CharField(choices=[('all_access', 'All Access'), ('video_only', 'Video Only'), ('authorized_access', 'Authorized Access')], default='all_access', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='is_zoom_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
