# Generated by Django 4.2 on 2025-12-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_access_type_student_is_zoom_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
