# Generated by Django 4.2 on 2025-12-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_topic_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='student_photos/'),
        ),
    ]
