# Generated by Django 4.2 on 2025-12-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='estimated_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='task_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
