# Generated by Django 4.2 on 2025-12-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_topic_deadline_topic_estimated_time_topic_task_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('review', 'Not Completed (On Review)')], default='pending', max_length=20),
        ),
    ]
