# Generated by Django 4.2 on 2025-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_completed', 'Not Completed'), ('review', 'On Review')], default='pending', max_length=20),
        ),
    ]
