# Generated by Django 4.2 on 2025-12-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_student_batch_alter_student_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password_plain',
        ),
        migrations.AddField(
            model_name='student',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
