# Generated by Django 4.2 on 2025-12-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_student_password_plain_student_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_amount',
        ),
        migrations.AddField(
            model_name='student',
            name='password_plain',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
