# Generated by Django 4.2 on 2025-12-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_remove_student_payment_amount_student_password_plain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password_plain',
        ),
    ]
