# Generated by Django 4.2 on 2025-12-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_remove_student_password_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password_plain',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
