# Generated by Django 4.2 on 2025-12-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_student_password_plain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password_plain',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
