# Generated by Django 4.2 on 2025-12-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_student_password_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
