# Generated by Django 4.2 on 2025-12-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
    ]
