# Generated by Django 4.2 on 2025-12-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
