# Generated by Django 4.2 on 2025-12-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_payment_admin_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content_type',
            field=models.CharField(choices=[('topic', 'Topic'), ('task', 'Task')], default='topic', max_length=10),
        ),
    ]
