# Generated by Django 4.2 on 2025-12-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_topic_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
    ]
