# Generated by Django 4.2 on 2025-12-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_remove_topic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_completed', 'Not Completed'), ('review', 'Review')], default='pending', max_length=20),
        ),
    ]
